# Generated by Django 5.2 on 2026-05-22 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('situacao', models.CharField(choices=[('aberto', 'Aberto'), ('ativo', 'Ativo'), ('aguardando_devolucao', 'Aguardando Devolução'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='aberto', max_length=25, verbose_name='Situação')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de saída')),
                ('km_saida', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM de saída')),
                ('combustivel_saida', models.CharField(blank=True, choices=[('vazio', 'Vazio'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('cheio', 'Cheio')], max_length=5, null=True, verbose_name='Combustível saída')),
                ('obs_saida', models.TextField(blank=True, verbose_name='Observações de saída')),
                ('data_devolucao_prevista', models.DateTimeField(verbose_name='Devolução prevista')),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True, verbose_name='Devolução real')),
                ('km_devolucao', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM de devolução')),
                ('combustivel_devolucao', models.CharField(blank=True, choices=[('vazio', 'Vazio'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('cheio', 'Cheio')], max_length=5, null=True, verbose_name='Combustível devolução')),
                ('obs_devolucao', models.TextField(blank=True, verbose_name='Observações de devolução')),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diária (R$)')),
                ('km_franquia_diaria', models.PositiveIntegerField(default=200, verbose_name='Franquia km/dia')),
                ('valor_km_excedente', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor km excedente (R$)')),
                ('caucao_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor caução (R$)')),
                ('caucao_situacao', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('devolvido_parcial', 'Devolvido Parcialmente'), ('devolvido', 'Devolvido'), ('retido', 'Retido')], default='pendente', max_length=20, verbose_name='Situação caução')),
                ('caucao_pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Caução pago em')),
                ('total_dias', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de dias')),
                ('dias_extras', models.PositiveSmallIntegerField(default=0, verbose_name='Dias extras')),
                ('km_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM total rodado')),
                ('km_excedente', models.PositiveIntegerField(default=0, verbose_name='KM excedente')),
                ('valor_km_excedente_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total KM excedente (R$)')),
                ('valor_dias_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total dias extras (R$)')),
                ('valor_diferenca_combustivel', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Diferença combustível (R$)')),
                ('token_assinatura', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token assinatura')),
                ('assinado_em', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP assinatura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='customers.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='fleet.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AvariaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização no veículo')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor cobrado (R$)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='contratos/avarias/', verbose_name='Foto')),
                ('situacao', models.CharField(choices=[('identificada', 'Identificada'), ('cobrada', 'Cobrada'), ('paga', 'Paga'), ('isenta', 'Isenta')], default='identificada', max_length=15, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avarias', to='contracts.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Avaria',
                'verbose_name_plural': 'Avarias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AdicionalContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gps', 'GPS'), ('cadeirinha', 'Cadeirinha'), ('condutor_adicional', 'Condutor Adicional'), ('seguro_basico', 'Seguro Básico'), ('seguro_completo', 'Seguro Completo'), ('outros', 'Outros')], max_length=25, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Diária (R$)')),
                ('quantidade', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='contracts.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionais',
            },
        ),
        migrations.CreateModel(
            name='FotoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('saida', 'Saída'), ('devolucao', 'Devolução')], max_length=10, verbose_name='Momento')),
                ('imagem', models.ImageField(upload_to='contratos/fotos/', verbose_name='Imagem')),
                ('posicao', models.CharField(choices=[('frente', 'Frente'), ('traseira', 'Traseira'), ('lateral_esq', 'Lateral esquerda'), ('lateral_dir', 'Lateral direita'), ('interior_frente', 'Interior frente'), ('interior_tras', 'Interior traseira'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Posição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='contracts.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Foto do Contrato',
                'verbose_name_plural': 'Fotos do Contrato',
                'ordering': ['momento', 'posicao'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('balcao', 'Balcão'), ('telefone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('site', 'Site'), ('app', 'Aplicativo')], default='balcao', max_length=20, verbose_name='Canal')),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('ativa', 'Ativa'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('no_show', 'No Show')], default='pendente', max_length=20, verbose_name='Situação')),
                ('data_retirada', models.DateTimeField(verbose_name='Data/hora de retirada')),
                ('data_devolucao', models.DateTimeField(verbose_name='Data/hora de devolução prevista')),
                ('diaria_cotada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diária cotada (R$)')),
                ('caucao_cotado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Caução cotado (R$)')),
                ('adicionais_cotados', models.JSONField(blank=True, default=dict, verbose_name='Adicionais cotados')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='customers.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('grupo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='fleet.grupoveiculo', verbose_name='Grupo de veículo')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='fleet.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_retirada'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato', to='contracts.reserva', verbose_name='Reserva'),
        ),
    ]
