# Generated by Django 5.2 on 2026-05-22 23:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('transferencia', 'Transferência Bancária'), ('cheque', 'Cheque')], max_length=20, verbose_name='Forma de Pagamento')),
                ('tipo', models.CharField(choices=[('locacao', 'Locação'), ('caucao', 'Caução'), ('adicional', 'Adicional'), ('avaria', 'Avaria/Dano'), ('multa', 'Multa de Trânsito'), ('outros', 'Outros')], default='locacao', max_length=20, verbose_name='Referente a')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/hora do pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='contracts.contrato', verbose_name='Contrato')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
