# Generated by Django 5.2 on 2026-05-23 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_parcelacontrato'),
        ('customers', '0002_alter_cliente_cnpj_alter_cliente_cpf_and_more'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionalcontrato',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='adicionalcontrato',
            name='diaria',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Diaria (R$)'),
        ),
        migrations.AlterField(
            model_name='adicionalcontrato',
            name='tipo',
            field=models.CharField(choices=[('gps', 'GPS'), ('cadeirinha', 'Cadeirinha'), ('condutor_adicional', 'Condutor Adicional'), ('seguro_basico', 'Seguro Basico'), ('seguro_completo', 'Seguro Completo'), ('outros', 'Outros')], max_length=25, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='avariacontrato',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='avariacontrato',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localizacao no veiculo'),
        ),
        migrations.AlterField(
            model_name='avariacontrato',
            name='situacao',
            field=models.CharField(choices=[('identificada', 'Identificada'), ('cobrada', 'Cobrada'), ('paga', 'Paga'), ('isenta', 'Isenta')], default='identificada', max_length=15, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='caucao_pago_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Caucao pago em'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='caucao_situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('devolvido_parcial', 'Devolvido Parcialmente'), ('devolvido', 'Devolvido'), ('retido', 'Retido')], default='pendente', max_length=20, verbose_name='Situacao caucao'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='caucao_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor caucao (R$)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='combustivel_devolucao',
            field=models.CharField(blank=True, choices=[('vazio', 'Vazio'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('cheio', 'Cheio')], max_length=5, null=True, verbose_name='Combustivel devolucao'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='combustivel_saida',
            field=models.CharField(blank=True, choices=[('vazio', 'Vazio'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('cheio', 'Cheio')], max_length=5, null=True, verbose_name='Combustivel saida'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_devolucao_prevista',
            field=models.DateTimeField(verbose_name='Devolucao prevista'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_devolucao_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Devolucao real'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de saida'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='diaria',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diaria (R$)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='km_devolucao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM de devolucao'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='km_saida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM de saida'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='obs_devolucao',
            field=models.TextField(blank=True, verbose_name='Observacoes de devolucao'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='obs_saida',
            field=models.TextField(blank=True, verbose_name='Observacoes de saida'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='situacao',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('ativo', 'Ativo'), ('aguardando_devolucao', 'Aguardando Devolucao'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='aberto', max_length=25, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_diferenca_combustivel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Diferenca combustivel (R$)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='fleet.veiculo', verbose_name='Veiculo'),
        ),
        migrations.AlterField(
            model_name='fotocontrato',
            name='momento',
            field=models.CharField(choices=[('saida', 'Saida'), ('devolucao', 'Devolucao')], max_length=10, verbose_name='Momento'),
        ),
        migrations.AlterField(
            model_name='fotocontrato',
            name='posicao',
            field=models.CharField(choices=[('frente', 'Frente'), ('traseira', 'Traseira'), ('lateral_esq', 'Lateral esquerda'), ('lateral_dir', 'Lateral direita'), ('interior_frente', 'Interior frente'), ('interior_tras', 'Interior traseira'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Posicao'),
        ),
        migrations.AlterField(
            model_name='pagamentocontrato',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartao de Credito'), ('cartao_debito', 'Cartao de Debito'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamentocontrato',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='pagamentocontrato',
            name='tipo',
            field=models.CharField(choices=[('locacao', 'Locacao'), ('caucao', 'Caucao'), ('adicional', 'Adicional'), ('avaria', 'Avaria/Dano'), ('multa', 'Multa de Transito'), ('outros', 'Outros')], default='locacao', max_length=20, verbose_name='Referente a'),
        ),
        migrations.AlterField(
            model_name='parcelacontrato',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartao de Credito'), ('cartao_debito', 'Cartao de Debito'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque')], max_length=20, null=True, verbose_name='Forma'),
        ),
        migrations.AlterField(
            model_name='parcelacontrato',
            name='numero',
            field=models.PositiveSmallIntegerField(verbose_name='No'),
        ),
        migrations.AlterField(
            model_name='parcelacontrato',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='parcelacontrato',
            name='origem',
            field=models.CharField(choices=[('original', 'Contrato Original'), ('prorrogacao', 'Prorrogacao')], default='original', max_length=15, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='parcelacontrato',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('em_atraso', 'Em Atraso'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='parcelacontrato',
            name='tipo',
            field=models.CharField(choices=[('caucao', 'Caucao'), ('semanal', 'Semanal')], default='semanal', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='canal',
            field=models.CharField(choices=[('balcao', 'Balcao'), ('telefone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('site', 'Site'), ('app', 'Aplicativo')], default='balcao', max_length=20, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='caucao_cotado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Caucao cotado (R$)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_devolucao',
            field=models.DateTimeField(verbose_name='Data/hora de devolucao prevista'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='diaria_cotada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diaria cotada (R$)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='grupo_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='fleet.grupoveiculo', verbose_name='Grupo de veiculo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('ativa', 'Ativa'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada'), ('no_show', 'No Show')], default='pendente', max_length=20, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='fleet.veiculo', verbose_name='Veiculo'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['situacao'], name='contracts_c_situaca_7fe450_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['cliente'], name='contracts_c_cliente_4bdb61_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['veiculo'], name='contracts_c_veiculo_6ac8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['data_devolucao_prevista'], name='contracts_c_data_de_6cf6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['data_saida'], name='contracts_c_data_sa_338a53_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelacontrato',
            index=models.Index(fields=['situacao'], name='contracts_p_situaca_874e40_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelacontrato',
            index=models.Index(fields=['data_vencimento'], name='contracts_p_data_ve_45153a_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelacontrato',
            index=models.Index(fields=['contrato', 'situacao'], name='contracts_p_contrat_b645a5_idx'),
        ),
    ]
