# Generated by Django 5.2 on 2026-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_adicionalcontrato_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='situacao',
            field=models.CharField(choices=[('aberto', 'Aguardando Saída'), ('ativo', 'Ativo'), ('aguardando_devolucao', 'Em Fechamento'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='aberto', max_length=25, verbose_name='Situacao'),
        ),
    ]
