# Generated by Django 5.2 on 2026-07-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_parcelacontrato_tipo_acerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='origem_retroativa',
            field=models.BooleanField(default=False, verbose_name='Origem retroativa/migração'),
        ),
    ]
