# Generated by Django 5.2 on 2026-07-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contrato_origem_retroativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocontrato',
            name='avaria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento_vinculado', to='contracts.avariacontrato', verbose_name='Avaria'),
        ),
        migrations.AddField(
            model_name='pagamentocontrato',
            name='parcela',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento_vinculado', to='contracts.parcelacontrato', verbose_name='Parcela'),
        ),
    ]
