# Generated by Django 5.2 on 2026-07-13 01:34

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_pagamentocontrato_avaria_pagamentocontrato_parcela_and_more'),
        ('customers', '0003_cliente_cliente_nome_trgm_idx'),
        ('fleet', '0003_veiculo_veiculo_placa_trgm_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('encerramento_antecipado', 'Encerramento Antecipado'), ('cancelamento', 'Cancelamento'), ('prorrogacao', 'Prorrogação')], max_length=30, verbose_name='Acao')),
                ('situacao_anterior', models.CharField(blank=True, max_length=25, verbose_name='Situacao anterior')),
                ('situacao_nova', models.CharField(blank=True, max_length=25, verbose_name='Situacao nova')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados adicionais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historico do Contrato',
                'verbose_name_plural': 'Historico dos Contratos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='encerrado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='encerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_encerrados_antecipadamente', to=settings.AUTH_USER_MODEL, verbose_name='Encerrado por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='encerramento_antecipado',
            field=models.BooleanField(default=False, verbose_name='Encerramento antecipado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='motivo_encerramento',
            field=models.CharField(blank=True, choices=[('cliente_solicitou', 'Solicitação do Cliente'), ('inadimplencia', 'Inadimplência'), ('problema_mecanico', 'Problema Mecânico'), ('substituicao_veiculo', 'Substituição de Veículo'), ('outro', 'Outro')], max_length=25, verbose_name='Motivo do encerramento antecipado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='motivo_encerramento_detalhe',
            field=models.TextField(blank=True, verbose_name='Detalhe do motivo'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=django.contrib.postgres.indexes.GinIndex(fields=['numero'], name='contrato_numero_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddField(
            model_name='historicocontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='contracts.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='historicocontrato',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='historicocontrato',
            index=models.Index(fields=['contrato', 'criado_em'], name='historico_contrato_data_idx'),
        ),
    ]
