# Generated by Django 5.2 on 2026-05-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=200, verbose_name='Nome do Contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=10, verbose_name='Situação')),
                ('motivo_bloqueio', models.TextField(blank=True, verbose_name='Motivo do bloqueio')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CNHCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11, verbose_name='Número')),
                ('estado_emissor', models.CharField(max_length=2, verbose_name='Estado emissor')),
                ('categoria', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('ab', 'AB'), ('ac', 'AC'), ('ad', 'AD'), ('ae', 'AE')], max_length=3, verbose_name='Categoria')),
                ('validade', models.DateField(verbose_name='Validade')),
                ('primeira_habilitacao', models.DateField(blank=True, null=True, verbose_name='Primeira habilitação')),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='clientes/cnh/', verbose_name='Foto frente')),
                ('foto_verso', models.ImageField(blank=True, null=True, upload_to='clientes/cnh/', verbose_name='Foto verso')),
                ('principal', models.BooleanField(default=True, verbose_name='CNH principal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnhs', to='customers.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'CNH',
                'verbose_name_plural': 'CNHs',
                'ordering': ['-principal', 'validade'],
            },
        ),
    ]
