# Generated by Django 5.2 on 2026-05-23 19:42

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, validators=[apps.core.validators.validar_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, validators=[apps.core.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razao Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='situacao',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=10, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('pf', 'Pessoa Fisica'), ('pj', 'Pessoa Juridica')], default='pf', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cnhcliente',
            name='numero',
            field=models.CharField(max_length=11, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='cnhcliente',
            name='primeira_habilitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Primeira habilitacao'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf'], name='customers_c_cpf_91cba0_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cnpj'], name='customers_c_cnpj_86f5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='customers_c_nome_f8fe6f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['situacao'], name='customers_c_situaca_cb8210_idx'),
        ),
    ]
