# Generated by Django 5.2 on 2026-07-13 01:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_cliente_cnpj_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nome'], name='cliente_nome_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
