# Generated by Django 5.2 on 2026-05-22 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_pagamentocontrato'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Troca de óleo, Revisão dos freios', max_length=200, verbose_name='Descrição')),
                ('tipo_alerta', models.CharField(choices=[('km', 'Por Quilometragem'), ('data', 'Por Data')], max_length=5, verbose_name='Tipo de alerta')),
                ('km_proximo_servico', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM do próximo serviço')),
                ('km_intervalo', models.PositiveIntegerField(blank=True, help_text='0 = não repetir', null=True, verbose_name='Repetir a cada X km')),
                ('data_proximo_servico', models.DateField(blank=True, null=True, verbose_name='Data do próximo serviço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_manutencao', to='fleet.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Alerta de Manutenção',
                'verbose_name_plural': 'Alertas de Manutenção',
                'ordering': ['veiculo', 'tipo_alerta'],
            },
        ),
        migrations.CreateModel(
            name='OrdemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('sinistro', 'Sinistro/Acidente')], default='preventiva', max_length=20, verbose_name='Tipo')),
                ('situacao', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20, verbose_name='Situação')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição do serviço')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('km_na_manutencao', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na manutenção')),
                ('data_agendada', models.DateField(blank=True, null=True, verbose_name='Data agendada')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Entrada na oficina')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Saída da oficina')),
                ('fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Oficina / Fornecedor')),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo total (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='contracts.contrato', verbose_name='Contrato relacionado')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='fleet.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Manutenção',
                'verbose_name_plural': 'Ordens de Manutenção',
                'ordering': ['-criado_em'],
            },
        ),
    ]
