# Generated by Django 5.2 on 2026-05-22 23:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_pagamentocontrato'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('manutencao', 'Manutenção'), ('seguro', 'Seguro'), ('ipva', 'IPVA'), ('licenciamento', 'Licenciamento / CRLV'), ('combustivel', 'Combustível'), ('lavagem', 'Lavagem / Higienização'), ('aluguel', 'Aluguel do Estabelecimento'), ('salario', 'Folha de Pagamento'), ('marketing', 'Marketing / Publicidade'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data_competencia', models.DateField(default=django.utils.timezone.now, verbose_name='Data de competência')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='fleet.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Despesa Operacional',
                'verbose_name_plural': 'Despesas Operacionais',
                'ordering': ['-data_competencia'],
            },
        ),
        migrations.CreateModel(
            name='MultaTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_auto', models.CharField(blank=True, max_length=30, verbose_name='Nº do Auto de Infração')),
                ('data_infracao', models.DateField(verbose_name='Data da Infração')),
                ('data_notificacao', models.DateField(blank=True, null=True, verbose_name='Data de Notificação')),
                ('prazo_indicacao', models.DateField(blank=True, null=True, verbose_name='Prazo para Indicar Condutor')),
                ('descricao', models.TextField(verbose_name='Descrição da Infração')),
                ('pontos', models.PositiveSmallIntegerField(default=0, verbose_name='Pontos')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('condutor_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do Condutor')),
                ('condutor_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF do Condutor')),
                ('situacao', models.CharField(choices=[('pendente_identificacao', 'Pendente — Identificar Condutor'), ('identificada', 'Condutor Identificado'), ('cobrada_cliente', 'Cobrada ao Cliente'), ('paga', 'Paga'), ('contestada', 'Em Contestação')], default='pendente_identificacao', max_length=30, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='contracts.contrato', verbose_name='Contrato')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='fleet.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Multa de Trânsito',
                'verbose_name_plural': 'Multas de Trânsito',
                'ordering': ['-data_infracao'],
            },
        ),
    ]
