# Generated by Django 5.2 on 2026-05-23 19:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_adicionalcontrato_descricao_and_more'),
        ('customers', '0002_alter_cliente_cnpj_alter_cliente_cpf_and_more'),
        ('financeiro', '0002_contareceber'),
        ('fleet', '0002_historicokmveiculo_alter_categoriaveiculo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLocadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_multa_atraso', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Percentual aplicado sobre o valor da parcela em atraso', max_digits=5, verbose_name='Multa por atraso (%)')),
                ('percentual_juros_diario', models.DecimalField(decimal_places=4, default=Decimal('0.0333'), help_text='1% ao mes = 0.0333% ao dia', max_digits=6, verbose_name='Juros diario (%)')),
                ('dias_carencia', models.PositiveSmallIntegerField(default=0, help_text='Dias apos o vencimento antes de aplicar multa e juros', verbose_name='Dias de carencia')),
            ],
            options={
                'verbose_name': 'Configuracao da Locadora',
                'verbose_name_plural': 'Configuracoes da Locadora',
            },
        ),
        migrations.AlterModelOptions(
            name='multatransito',
            options={'ordering': ['-data_infracao'], 'verbose_name': 'Multa de Transito', 'verbose_name_plural': 'Multas de Transito'},
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='data_emissao',
            field=models.DateField(verbose_name='Data de Emissao'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago_parcial', 'Pago Parcialmente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='despesaoperacional',
            name='categoria',
            field=models.CharField(choices=[('manutencao', 'Manutencao'), ('seguro', 'Seguro'), ('ipva', 'IPVA'), ('licenciamento', 'Licenciamento / CRLV'), ('combustivel', 'Combustivel'), ('lavagem', 'Lavagem / Higienizacao'), ('aluguel', 'Aluguel do Estabelecimento'), ('salario', 'Folha de Pagamento'), ('marketing', 'Marketing / Publicidade'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesaoperacional',
            name='data_competencia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de competencia'),
        ),
        migrations.AlterField(
            model_name='despesaoperacional',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='despesaoperacional',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='despesaoperacional',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='fleet.veiculo', verbose_name='Veiculo'),
        ),
        migrations.AlterField(
            model_name='multatransito',
            name='data_infracao',
            field=models.DateField(verbose_name='Data da Infracao'),
        ),
        migrations.AlterField(
            model_name='multatransito',
            name='data_notificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Notificacao'),
        ),
        migrations.AlterField(
            model_name='multatransito',
            name='descricao',
            field=models.TextField(verbose_name='Descricao da Infracao'),
        ),
        migrations.AlterField(
            model_name='multatransito',
            name='numero_auto',
            field=models.CharField(blank=True, max_length=30, verbose_name='No do Auto de Infracao'),
        ),
        migrations.AlterField(
            model_name='multatransito',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='multatransito',
            name='situacao',
            field=models.CharField(choices=[('pendente_identificacao', 'Pendente - Identificar Condutor'), ('identificada', 'Condutor Identificado'), ('cobrada_cliente', 'Cobrada ao Cliente'), ('paga', 'Paga'), ('contestada', 'Em Contestacao')], default='pendente_identificacao', max_length=30, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='multatransito',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='fleet.veiculo', verbose_name='Veiculo'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['situacao'], name='financeiro__situaca_3e60a5_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_9e57f0_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente'], name='financeiro__cliente_3de520_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaoperacional',
            index=models.Index(fields=['data_competencia'], name='financeiro__data_co_c9e01a_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaoperacional',
            index=models.Index(fields=['categoria'], name='financeiro__categor_d352bb_idx'),
        ),
    ]
