# Generated by Django 5.2 on 2026-05-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_despesaoperacional_debito_automatico'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='despesaoperacional',
            new_name='financeiro__parcela_aaf341_idx',
            old_name='financeiro_despesa_parcelado_idx',
        ),
        migrations.RenameIndex(
            model_name='parceladespesa',
            new_name='financeiro__situaca_7f42d6_idx',
            old_name='financeiro_parcela_situacao_idx',
        ),
        migrations.RenameIndex(
            model_name='parceladespesa',
            new_name='financeiro__data_ve_6fed9d_idx',
            old_name='financeiro_parcela_vencimento_idx',
        ),
        migrations.RenameIndex(
            model_name='parceladespesa',
            new_name='financeiro__despesa_d6f8eb_idx',
            old_name='financeiro_parcela_despesa_sit_idx',
        ),
    ]
