# Generated by Django 5.2 on 2026-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_rename_financeiro_despesa_parcelado_idx_financeiro__parcela_aaf341_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceladespesa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto Bancário'), ('transferencia', 'Transferência Bancária'), ('debito_automatico', 'Débito Automático')], max_length=20, verbose_name='Forma de pagamento'),
        ),
    ]
