# Generated by Django 5.2 on 2026-05-22 22:59

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200, verbose_name='Nome da locadora')),
                ('slug', models.SlugField(unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('plan', models.CharField(choices=[('basic', 'Básico — até 10 veículos'), ('professional', 'Profissional — até 30 veículos'), ('premium', 'Premium — ilimitado')], default='basic', max_length=20, verbose_name='Plano')),
                ('is_active', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Locadora',
                'verbose_name_plural': 'Locadoras',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenantcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
