# Generated by Django 5.2 on 2026-06-11 01:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_historicokmveiculo_alter_categoriaveiculo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('dados_bancarios', models.TextField(blank=True, help_text='Banco, agência, conta corrente, chave PIX…', verbose_name='Dados bancários')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investidor',
                'verbose_name_plural': 'Investidores',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['situacao'], name='investidore_situaca_8ac885_idx'), models.Index(fields=['nome'], name='investidore_nome_5b5e36_idx')],
            },
        ),
        migrations.CreateModel(
            name='VeiculoInvestidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_gestao_semanal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa de gestão semanal (R$)')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, help_text='Dia do mês em que as cobranças vencem (1 a 28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Dia de vencimento')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='investidores.investidor', verbose_name='Investidor')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculo_investidor', to='fleet.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Vínculo Veículo–Investidor',
                'verbose_name_plural': 'Vínculos Veículo–Investidor',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaGestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Semana início')),
                ('semana_fim', models.DateField(verbose_name='Semana fim')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Situação')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('boleto', 'Boleto')], max_length=15, verbose_name='Forma de pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo_investidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='investidores.veiculoinvestidor', verbose_name='Vínculo')),
            ],
            options={
                'verbose_name': 'Cobrança de Gestão',
                'verbose_name_plural': 'Cobranças de Gestão',
                'ordering': ['-semana_inicio', 'veiculo_investidor__investidor__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='veiculoinvestidor',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('veiculo',), name='unico_vinculo_ativo_por_veiculo'),
        ),
        migrations.AddIndex(
            model_name='cobrancagestao',
            index=models.Index(fields=['situacao'], name='investidore_situaca_9a8301_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancagestao',
            index=models.Index(fields=['data_vencimento'], name='investidore_data_ve_ba5090_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancagestao',
            index=models.Index(fields=['veiculo_investidor', 'semana_inicio'], name='investidore_veiculo_e22b05_idx'),
        ),
    ]
