# Generated by Django 5.2 on 2026-05-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Categoria')),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone, ex: fa-car', max_length=60, verbose_name='Ícone CSS')),
                ('cor', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor hex')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Veículo',
                'verbose_name_plural': 'Categorias de Veículos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do grupo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diária (R$)')),
                ('semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Semanal (R$)')),
                ('mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mensal (R$)')),
                ('km_franquia_diaria', models.PositiveIntegerField(default=200, verbose_name='Franquia km/dia')),
                ('valor_km_excedente', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor km excedente (R$)')),
                ('caucao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Caução (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='fleet.categoriaveiculo', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Grupo de Veículo',
                'verbose_name_plural': 'Grupos de Veículos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('chassi', models.CharField(blank=True, max_length=17, verbose_name='Chassi')),
                ('renavam', models.CharField(blank=True, max_length=11, verbose_name='RENAVAM')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo')),
                ('ano_fabricacao', models.PositiveSmallIntegerField(verbose_name='Ano fabricação')),
                ('ano_modelo', models.PositiveSmallIntegerField(verbose_name='Ano modelo')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('combustivel', models.CharField(choices=[('flex', 'Flex'), ('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido')], default='flex', max_length=20, verbose_name='Combustível')),
                ('transmissao', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('cvt', 'CVT')], default='manual', max_length=20, verbose_name='Transmissão')),
                ('portas', models.PositiveSmallIntegerField(default=4, verbose_name='Portas')),
                ('lugares', models.PositiveSmallIntegerField(default=5, verbose_name='Lugares')),
                ('km_atual', models.PositiveIntegerField(default=0, verbose_name='KM atual')),
                ('situacao', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Situação')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de aquisição (R$)')),
                ('valor_fipe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor FIPE (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='fleet.grupoveiculo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='FotoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='veiculos/fotos/', verbose_name='Imagem')),
                ('posicao', models.CharField(choices=[('frente', 'Frente'), ('traseira', 'Traseira'), ('lateral_esq', 'Lateral esquerda'), ('lateral_dir', 'Lateral direita'), ('interior_frente', 'Interior frente'), ('interior_tras', 'Interior traseira'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Posição')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('principal', models.BooleanField(default=False, verbose_name='Foto principal')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='fleet.veiculo')),
            ],
            options={
                'verbose_name': 'Foto do Veículo',
                'verbose_name_plural': 'Fotos do Veículo',
                'ordering': ['-principal', 'posicao'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('crlv', 'CRLV'), ('seguro', 'Seguro'), ('extintor', 'Extintor'), ('vistoria', 'Vistoria'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Número')),
                ('emissor', models.CharField(blank=True, max_length=100, verbose_name='Emissor')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='veiculos/documentos/', verbose_name='Arquivo')),
                ('dias_alerta', models.PositiveSmallIntegerField(default=30, verbose_name='Alertar X dias antes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='fleet.veiculo')),
            ],
            options={
                'verbose_name': 'Documento do Veículo',
                'verbose_name_plural': 'Documentos do Veículo',
                'ordering': ['tipo', 'data_validade'],
            },
        ),
    ]
