# Generated by Django 5.2 on 2026-05-23 19:42

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_adicionalcontrato_descricao_and_more'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoKmVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.PositiveIntegerField(verbose_name='KM')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/hora')),
                ('origem', models.CharField(choices=[('contrato_saida', 'Saida de Contrato'), ('contrato_devolucao', 'Devolucao de Contrato'), ('manutencao', 'Manutencao'), ('manual', 'Atualizacao Manual')], max_length=25, verbose_name='Origem')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historico de KM',
                'verbose_name_plural': 'Historico de KM',
                'ordering': ['-data'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoriaveiculo',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria de Veiculo', 'verbose_name_plural': 'Categorias de Veiculos'},
        ),
        migrations.AlterModelOptions(
            name='documentoveiculo',
            options={'ordering': ['tipo', 'data_validade'], 'verbose_name': 'Documento do Veiculo', 'verbose_name_plural': 'Documentos do Veiculo'},
        ),
        migrations.AlterModelOptions(
            name='fotoveiculo',
            options={'ordering': ['-principal', 'posicao'], 'verbose_name': 'Foto do Veiculo', 'verbose_name_plural': 'Fotos do Veiculo'},
        ),
        migrations.AlterModelOptions(
            name='grupoveiculo',
            options={'ordering': ['categoria', 'nome'], 'verbose_name': 'Grupo de Veiculo', 'verbose_name_plural': 'Grupos de Veiculos'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['marca', 'modelo'], 'verbose_name': 'Veiculo', 'verbose_name_plural': 'Veiculos'},
        ),
        migrations.AlterField(
            model_name='categoriaveiculo',
            name='icone',
            field=models.CharField(blank=True, max_length=60, verbose_name='Icone CSS'),
        ),
        migrations.AlterField(
            model_name='documentoveiculo',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissao'),
        ),
        migrations.AlterField(
            model_name='documentoveiculo',
            name='numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='fotoveiculo',
            name='posicao',
            field=models.CharField(choices=[('frente', 'Frente'), ('traseira', 'Traseira'), ('lateral_esq', 'Lateral esquerda'), ('lateral_dir', 'Lateral direita'), ('interior_frente', 'Interior frente'), ('interior_tras', 'Interior traseira'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Posicao'),
        ),
        migrations.AlterField(
            model_name='grupoveiculo',
            name='caucao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Caucao (R$)'),
        ),
        migrations.AlterField(
            model_name='grupoveiculo',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='grupoveiculo',
            name='diaria',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diaria (R$)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.PositiveSmallIntegerField(verbose_name='Ano fabricacao'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('flex', 'Flex'), ('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('eletrico', 'Eletrico'), ('hibrido', 'Hibrido')], default='flex', max_length=20, verbose_name='Combustivel'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aquisicao'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, unique=True, validators=[apps.core.validators.validar_placa], verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='situacao',
            field=models.CharField(choices=[('disponivel', 'Disponivel'), ('reservado', 'Reservado'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutencao'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='transmissao',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automatico'), ('cvt', 'CVT')], default='manual', max_length=20, verbose_name='Transmissao'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='valor_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de aquisicao (R$)'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['situacao'], name='fleet_veicu_situaca_ccba02_idx'),
        ),
        migrations.AddField(
            model_name='historicokmveiculo',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_km', to='contracts.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='historicokmveiculo',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicokmveiculo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_km', to='fleet.veiculo', verbose_name='Veiculo'),
        ),
        migrations.AddIndex(
            model_name='historicokmveiculo',
            index=models.Index(fields=['veiculo', 'data'], name='fleet_histo_veiculo_dc97a6_idx'),
        ),
    ]
