# Generated by Django 5.2 on 2026-07-13 01:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_historicokmveiculo_alter_categoriaveiculo_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='veiculo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['placa'], name='veiculo_placa_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
